nodeLinker: node-modules

# Enable zero-installs for faster builds
enableGlobalCache: true

# Use frozen lockfile for reproducible builds
enableImmutableInstalls: false

# Enable PnP for better performance
pnpMode: loose
